version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: ./docker/Dockerfile
    container_name: dojo-app-gs-kata
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: dojo-nginx-gs-kata
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
